image: renovate/renovate:36-full

DEBUG Update Web Project:
  variables:
    LOG_LEVEL: debug
    RENOVATE_TOKEN: $RENOVATE_WEB_TOKEN
    RENOVATE_COMPOSER_IGNORE_PLATFORM_REQS: 'false'
  script:
    - renovate $RENOVATE_EXTRA_FLAGS 2>1 | tee job_output.txt
  when: manual
  artifacts:
    paths:
      - job_output.txt

