image: renovate/renovate:36-full

test:
  variables:
    LOG_LEVEL: debug
    RENOVATE_TOKEN: $RENOVATE_WEB_TOKEN
    RENOVATE_COMPOSER_IGNORE_PLATFORM_REQS: 'false'
  script:
    - renovate --platform=local
  artifacts:
    paths:
      - job_output.txt

